apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-configmap
  namespace: n8n-devs
  labels:
    app: n8n
    component: configmap
data:
  DB_TYPE: "postgresdb"
  DB_TABLE_PREFIX: "n8n"
  DB_POSTGRESDB_USER: "n8n"
  DB_POSTGRESDB_DATABASE: "n8n"
  DB_POSTGRESDB_HOST: "postgres-service"
  DB_POSTGRESDB_PORT: "5432"
  EXECUTIONS_MODE: "queue" 
  QUEUE_BULL_REDIS_HOST: "redis-service"
  QUEUE_BULL_REDIS_PORT: "6379"