apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: n8n-devs
spec:
  replicas: 1
  serviceName: postgres-statefulset
  selector:
    matchLabels:
      app: postgres
      component: statefulset

  template:
    metadata:
      labels:
        app: postgres
        component: statefulset

    spec:
      containers:
        - name: postgres
          image: postgres:16

          ports:
            - containerPort: 5432
              name: postgres

          envFrom:
            - secretRef:
                name: postgres-secrets

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "2Gi"

          startupProbe:
            exec:
              command: ["pg_isready"]
            failureThreshold: 30
            periodSeconds: 5

          readinessProbe:
            exec:
              command: ["pg_isready"]
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            exec:
              command: ["pg_isready"]
            initialDelaySeconds: 30
            periodSeconds: 10

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi