apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-statefulset
  namespace: n8n-devs
  labels: &labels
    app: redis
    component: statefulset
spec:
  serviceName: redis-statefulset
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - name: redis
          containerPort: 6379